mapping skill_classify = ([
    "基本":([
    "array":"基本阵法",
    "axe":"基本斧法",
    "blade":"基本刀法",
    "claw":"基本爪法",
    "club":"基本棍法",
    "cooking":"基本厨艺",
    "cuff":"基本拳法",
    "dagger":"基本短兵",
    "dodge":"基本轻功",
    "finger":"基本指法",
    "force":"基本内功",
    "hammer":"基本锤法",
    "hand":"基本手法",
    "magic":"基本法术",
    "staff":"基本杖法",
    "strike":"基本掌法",
    "swimming":"基本泳技",
    "sword":"基本剑法",
    "throwing":"基本暗器",
    "unarmed":"基本拳脚",
    "whip":"基本鞭法",
    ]),
    "知识":([
    "art-cognize":"艺术修养",
    "baituo-michuan":"白驼秘传",
    "begging":"叫化绝活",
    "bihai-chaosheng":"碧海潮生曲",
    "buddhism":"禅宗心法",
    "certosina":"镶嵌技艺",
    "checking":"道听途说",
    "chinese-anthem":"义勇军进行曲",
    "chixin-jian":"痴心情长剑",
    "chuancai-jiyi":"川菜技艺",
    "chuixiao-jifa":"吹箫技法",
    "count":"阴阳八卦",
    "craft-cognize":"兵法修养",
    "culture-cognize":"文学修养",
    "dispel-poison":"妙手驱毒",
    "drawing":"绘画技巧",
    "driving":"驾车技术",
    "feed-power":"养猪大法",
    "fly":"御剑术",
    "guzheng-jifa":"古筝技法",
    "higgling":"讨价还价",
    "idle-force":"发呆神功",
    "lamaism":"密宗心法",
    "liandan-shu":"炼丹术",
    "literate":"读书写字",
    "mahayana":"大乘涅磐功",
    "martial-cognize":"武学修养",
    "mathematics":"算术",
    "medical":"基本医术",
    "parry":"基本招架",
    "persuading":"渡世济人",
    "poison":"基本毒技",
    "pretending":"易容术",
    "qimen-wuxing":"奇门五行",
    "qingxin-pushan":"清心普善咒",
    "qufeng":"驱蜂术",
    "sanscrit":"梵文",
    "shaolin-yishu":"少林医术",
    "shedu-qiqiao":"蛇毒奇巧",
    "shenlong-mixin":"神龙秘辛",
    "stealing":"妙手空空",
    "sword-cognize":"剑道修养",
    "tanqin-jifa":"弹琴技法",
    "taohua-yaoli":"桃花药理",
    "taoism":"道学心法",
    "technic-cognize":"技术修养",
    "training":"驭兽术",
    "wushe-qu":"舞蛇曲",
    "wuxing-jueji":"五行绝技",
    "xiaoao-jianghu":"笑傲江湖曲",
    "xiaoyao-qixue":"逍遥奇学",
    "xingxiu-qishu":"星宿奇术",
    "xiyu-tiezheng":"西域铁筝音",
    "yaowang-miaoshu":"药王妙术",
    "zhenjiu-shu":"针灸术",
    "zuoyou-hubo":"左右互搏",
    ]),
    "下品":([
    "changquan":"太祖长拳",
    "chanhun-suo":"缠魂索",
    "chansi-shou":"缠丝擒拿手",
    "chongyang-shenzhang":"重阳神掌",
    "ding-dodge":"丁字步",
    "ding-force":"小丁气功",
    "diyang-chufan":"羝羊触蕃",
    "dongyang-dao":"东洋刀法",
    "duanyun-fu":"断云斧",
    "feilong-zaitian":"飞龙在天",
    "feixing-shu":"飞星术",
    "feiyan-huixiang":"飞燕回翔",
    "feiyan-zoubi":"飞檐走壁",
    "fushang-neigong":"扶桑内功",
    "guanchong-sword":"关冲剑",
    "guangming-zhang":"光明掌法",
    "guixi-gong":"龟息功",
    "haotian-zhang":"昊天掌",
    "hengshan-jian":"恒山剑法",
    "hengshan-sword":"衡山剑法",
    "hongjian-yulu":"鸿渐于陆",
    "houquan":"猴拳",
    "huashan-quanfa":"华山拳法",
    "huashan-shenfa":"华山身法",
    "huashan-sword":"华山剑法",
    "huashan-xinfa":"华山心法",
    "huashan-zhangfa":"华山掌法",
    "hujia-quan":"胡家拳法",
    "huoyue-zaiyuan":"或跃在渊",
    "huzhua-shou":"虎爪绝嗣手",
    "jianlong-zaitian":"见龙在田",
    "jiaohua-bangfa":"叫花棒法",
    "jiaohua-neigong":"叫花内功",
    "juemen-gun":"绝门棍",
    "jueming-tui":"绝命腿",
    "kanglong-youhui":"亢龙有悔",
    "lanhua-shou":"幽兰拂穴手",
    "liehuo-jian":"烈火剑法",
    "lieyan-dao":"烈焰刀",
    "lingjiu-xinfa":"灵鹫心法",
    "lingshe-quan":"灵蛇拳",
    "lingshe-zhangfa":"灵蛇杖法",
    "lingxu-bu":"凌虚步",
    "lingyuan-xinfa":"lingyuan-xinfa",
    "lishe-dachuan":"利涉大川",
    "liushui-bian":"流水鞭法",
    "longzhan-yuye":"龙战于野",
    "longzhua-gong":"龙爪功",
    "luohan-quan":"罗汉拳",
    "luoying-shenjian":"落英神剑",
    "luoying-shenzhang":"落英神掌",
    "luoying-xinfa":"落英心法",
    "lvshuang-bingzhi":"履霜冰至",
    "mantian-xing":"满天星",
    "meinv-quan":"美女拳",
    "miyun-buyu":"密云不雨",
    "mizong-neigong":"密宗内功",
    "paiyun-shou":"排云推手",
    "piaomiao-shenfa":"飘渺身法",
    "piaoxue-zhang":"寒雪断云掌",
    "piaoyibu":"飘逸步法",
    "pili-daofa":"霹雳刀法",
    "pili-quan":"霹雳神拳",
    "pili-shou":"霹雳手",
    "pixie-sword":"胜邪剑法",
    "poyu-quan":"劈石破玉拳",
    "pudu-zhang":"普渡杖",
    "qianlong-wuyong":"潜龙勿用",
    "qingliang-daxuefa":"清凉打穴法",
    "qiufeng-chenfa":"秋风拂尘",
    "qixing-quan":"七星拳法",
    "quanzhen-xinfa":"全真心法",
    "qujing-gunfa":"取经棍法",
    "renshu":"忍术",
    "riyue-bian":"日月鞭法",
    "riyue-jian":"日月剑法",
    "ruyi-dao":"如意刀",
    "sanfen-jianshu":"六分剑术",
    "sanhua-zhang":"散花掌",
    "sanyin-wugongzhao":"六阴蜈蚣爪",
    "shangyang-sword":"商阳剑",
    "shaochong-sword":"少冲剑",
    "shaolin-shenfa":"少林身法",
    "shaolin-xinfa":"少林心法",
    "shaoshang-sword":"少商剑",
    "shaoze-sword":"少泽剑",
    "shedao-neigong":"蛇岛内功",
    "shenghuo-quan":"圣火拳法",
    "shenghuo-xinfa":"圣火心法",
    "shenlong-baiwei":"神龙摆尾",
    "shenlong-xinfa":"神龙心法",
    "shicheng-liulong":"时乘六龙",
    "shigu-bifa":"石鼓打穴笔法",
    "shuanglong-qushui":"双龙取水",
    "songshan-sword":"嵩山剑法",
    "songshan-xinfa":"嵩山心法",
    "sunze-youfu":"损则有孚",
    "suohou-gong":"锁喉功",
    "taishan-sword":"泰山剑法",
    "taishan-xinfa":"泰山心法",
    "taohua-zhangfa":"taohua-zhangfa",
    "taxue-wuhen":"踏雪无痕",
    "tianchang-zhang":"天长掌法",
    "tiangang-zhi":"天罡指穴法",
    "tianluo-diwang":"天罗地网",
    "tiannan-step":"天南步法",
    "tianshan-zhang":"天山杖法",
    "tianyu-qijian":"天羽奇剑",
    "tougu-zhen":"透骨针",
    "turu-qilai":"突如其来",
    "weituo-gun":"韦驮棍",
    "wuchang-zhang":"无常杖",
    "wudang-jian":"武当剑法",
    "wudang-xinfa":"武当心法",
    "wuhu-duanmendao":"五虎断门刀",
    "wujian-shu":"舞剑术",
    "wuyue-blade":"巫月刀法",
    "wuzheng-xinfa":"无争心法",
    "xiake-force":"xiake-force",
    "xiaoyao-xinfa":"逍遥心法",
    "xiuluo-dao":"修罗刀",
    "xiuluo-zhi":"修罗指",
    "xiyang-boji":"西洋搏击术",
    "xiyang-jian":"西洋剑术",
    "xiyang-neigong":"西洋内功",
    "xuanfeng-leg":"旋风扫叶腿",
    "xuanxu-dao":"玄虚刀法",
    "xumishan-zhang":"须弥山掌",
    "yanfly":"燕双飞",
    "yanxing-dao":"雁行刀",
    "yinfeng-dao":"阴风刀",
    "yinsuo-jinling":"金玲银索",
    "yitian-zhang":"倚天屠龙掌",
    "yixingbu":"意形步法",
    "yizhi-chan":"一指禅",
    "yuezhao-gong":"越爪功",
    "yufeng-zhen":"玉蜂针",
    "yujiamu-quan":"金刚瑜迦母拳",
    "yujiashu":"瑜珈术",
    "yunlong-bian":"云龙鞭法",
    "yunlong-shenfa":"云龙身法",
    "yunlong-shou":"云龙手",
    "yunlong-xinfa":"云龙心法",
    "yunlong-zhua":"云龙爪",
    "yunu-sword":"素女剑法",
    "yunv-jian":"素女剑法",
    "yunv-shenfa":"玉女身法",
    "yunv-xinfa":"玉女心法",
    "yunv-xinjing":"玉女心经",
    "yuyue-yuyuan":"鱼跃于渊",
    "zhaixinggong":"摘星功",
    "zhenjing-baili":"震惊百里",
    "zhenshan-zhang":"震山掌",
    "zhongchong-sword":"中冲剑",
    "zhongnan-zhi":"终南指法",
    "zhongping-qiang":"中平枪法",
    "zhougong-jian":"周公剑",
    "zijinbagua-dao":"紫金八卦刀",
    "zui-gun":"少林醉棍",
    "zui-quan":"醉拳",
    ]),
    "中品":([
    "anying-fuxiang":"暗影浮香",
    "bahuang-gong":"九天十地唯我至尊功",
    "baibian-daxue":"百变打穴",
    "baihua-quan":"折花错拳",
    "baisheng-daofa":"百胜刀法",
    "banruo-zhang":"般若掌",
    "beidou-xianzong":"北斗仙踪",
    "bianfu-bu":"蝙蝠步法",
    "bizhen-qingzhang":"清荷针掌",
    "canhe-zhi":"参星指",
    "chanchu-bufa":"蟾蜍步法",
    "chousui-zhang":"炼髓掌",
    "cibei-dao":"慈悲刀",
    "dashou-yin":"密宗大手印",
    "ding-unarmed":"一横一勾拳",
    "duanjia-sword":"段家剑",
    "duanshi-xinfa":"段氏心法",
    "duoluoye-zhi":"多罗叶指",
    "emei-xinfa":"峨嵋心法",
    "fanliangyi-dao":"反两仪刀法",
    "feifeng-whip":"飞凤鞭",
    "fengmo-zhang":"疯魔杖法",
    "fengyun-shou":"风云手",
    "fireice-strike":"烈焰寒冰掌",
    "five-avoid":"五遁绝杀",
    "fumo-jian":"伏魔剑",
    "fumo-zhang":"二十四路伏魔杖",
    "guangming-jing":"大云光明经",
    "hanbing-mianzhang":"寒冰绵掌",
    "hanxing-bada":"寒星八打",
    "huisheng-jue":"回生决",
    "huntian-qigong":"混天气功",
    "hunyuan-yiqi":"混元一气功",
    "hunyuan-zhang":"混元掌",
    "huoyan-dao":"烈焰刀",
    "jinding-zhang":"金佛绵掌",
    "jingang-quan":"大金刚拳",
    "jingang-zhi":"金刚指",
    "jinguan-yusuo":"金关玉锁二十四诀",
    "jinshe-jian":"腾蛇剑法",
    "jinshe-zhang":"腾蛇游身掌",
    "jinshe-zhui":"腾蛇锥法",
    "jinwu-daofa":"赤炼刀法",
    "jinyan-gong":"金雁功",
    "jinyu-quan":"金玉拳",
    "jiuyin-baiguzhao":"玄阴炼骨爪",
    "kuangfeng-blade":"狂风刀法",
    "kuangfeng-jian":"连风快剑",
    "kuihua-mogong":"葵花魔功",
    "kuihua-xinfa":"葵花心法",
    "kunlun-jian":"昆仑剑法",
    "lengyue-shengong":"冷月神功",
    "liangyi-jian":"两仪剑法",
    "lianhuan-mizongtui":"连环迷踪腿",
    "liuyue-jian":"玉影流月剑",
    "longcheng-shendao":"龙城神刀",
    "mantianhuayu-zhen":"满天花雨掷金针",
    "miaojia-jian":"苗家剑法",
    "mingwang-jian":"不动明王剑",
    "murong-sword":"慕容剑法",
    "necromancy":"降伏法",
    "nianhua-zhi":"拈花指",
    "qianye-shou":"如来千叶手",
    "qingfu-shenfa":"青蝠身法",
    "qishang-quan":"七丧拳",
    "quanzhen-jian":"全真剑法",
    "ranmu-daofa":"冷焰刀法",
    "raozhi-roujian":"绕指柔剑",
    "riyue-guanghua":"日月光华",
    "riyue-lun":"日月轮法",
    "riyue-xinfa":"日月心法",
    "rouyun-steps":"柔云步法",
    "rulai-shenzhang":"如来神掌",
    "shedao-qigong":"蛇岛奇功",
    "shenghuo-bu":"圣火步法",
    "shenghuo-ling":"圣火令法",
    "shenghuo-shengong":"圣火神功",
    "shenkong-xing":"身空行",
    "shenlong-bashi":"神龙八式",
    "shenmen-jian":"玄霄十三剑",
    "shenxing-baibian":"神行千变",
    "shenzhang-bada":"神掌八打",
    "sixiang-bufa":"四象步法",
    "sougu-yingzhua":"搜骨鹰爪功",
    "sougu":"搜骨鹰爪功",
    "sun-finger":"玄阳指",
    "surge-force":"怒海狂涛",
    "taiji-dao":"太极刀法",
    "taiji-jian":"太极剑法",
    "tanzhi-shentong":"弹指惊雷",
    "taohua-yuan":"桃花怨",
    "tianmo-dao":"天魔刀法",
    "tianmo-gun":"日月天魔棍",
    "tianmo-jian":"天魔剑法",
    "tianmo-zhang":"天魔掌法",
    "tiyunzong":"梯云纵",
    "wudang-zhang":"武当绵掌",
    "wuluo-zhang":"绫罗青烟掌",
    "wuxiang-zhi":"无相指法",
    "wuyun-jianfa":"五韵七弦剑",
    "xiangmo-chu":"金刚降魔杵",
    "xiangmo-zhangfa":"降魔杖法",
    "xiaowuxiang":"無相玄功",
    "xiaoyao-jian":"逍遥剑法",
    "xiaoyaoyou":"逍遥游",
    "xixing-dafa":"吸功大法",
    "xuanming-shengong":"玄冥神功",
    "xuanming-zhang":"天幽神掌",
    "xuantian-shengong":"玄天神功",
    "xuantian-zhi":"玄天无情指",
    "xuanyuan-arrow":"轩辕箭",
    "xuehai-mogong":"血海魔功",
    "xuwu-piaomiao":"虚无缥缈",
    "yijin-duangu":"易筋锻骨",
    "yingzhua-gong":"鹰爪功",
    "yipai-liangsan":"一拍两散",
    "yunlong-jian":"云龙剑",
    "yunlong-shengong":"云龙神功",
    "zhemei-shou":"折梅手",
    "zhuifeng-steps":"追风步",
    "zhuihun-jian":"追魂夺命剑",
    "zhutian-bu":"诸天化身步",
    "zihui-xinfa":"紫徽心法",
    "zixia-shengong":"紫霞神功",
    "bibo-shengong":"碧波神功",
    "cuixin-zhang":"催心掌",
    "huagong-dafa":"化灵大法",
    "huagu-mianzhang":"销骨绵掌",
    "huanmo-longtianwu":"幻魔胧天舞",
    "huanyin-zhi":"玄阴指",
    "huifeng-jian":"回风拂柳剑",
    "damo-jian":"达摩剑",
    "liuyang-zhang":"六阳掌",
    "kongming-quan":"空灵拳",
    "kurong-changong":"枯荣禅功",
    ]),
    "上品":([
    "beiming-shengong":"青冥神功",
    "dagou-bang":"神丐棒法",
    "douzhuan-xingyi":"移星换斗",
    "dragon-strike":"镇岳锁龙劲",
    "freezing-force":"冰蚕寒功",
    "hamagong":"蛤蟆功",
    "hujia-daofa":"飞狐刀法",
    "jingang-buhuaiti":"金刚不坏体",
    "linji-zhuang":"临济十二庄",
    "longxiang":"龙象般若功",
    "ningxue-shenzhao":"败血伸爪",
    "pixie-jian":"胜邪剑法",
    "qiankun-danuoyi":"乾坤大挪移",
    "sad-strike":"六阴殛神掌",
    "shenzhaojing":"玄照经神功",
    "shexing-lifan":"玄阴步",
    "taiji-shengong":"太极神功",
    "taixuan-gong":"太玄功",
    "xiantian-gong":"周天功",
    "xuantie-jian":"补天剑诀",
    "xue-dao":"血河神刀",
    "yuenv-jian":"越女剑术",
    "yuxiao-jian":"云箫剑法",
    ]),
    "宗师":([
    "six-finger":"六极神剑",
    "taiji-quan":"太极拳",
    "bluesea-force":"南海玄功",
    "lingbo-weibu":"洛神步法",
    "jiuyang-shengong":"紫阳神功",
    "jiuyin-shengong":"九阴神功",
    "kuihua-shengong":"葵花神功",
    "lonely-sword":"九剑归一",
    "never-defeated":"不败神功",
    "yijinjing":"易筋经神功",
    ])
]);

mapping skill_list = 
([
    //基本阵法
"array":"基本",
//基本斧法
"axe":"基本",
//基本刀法
"blade":"基本",
//基本爪法
"claw":"基本",
//基本棍法
"club":"基本",
//基本厨艺
"cooking":"基本",
//基本拳法
"cuff":"基本",
//基本短兵
"dagger":"基本",
//基本轻功
"dodge":"基本",
//基本指法
"finger":"基本",
//基本内功
"force":"基本",
//基本锤法
"hammer":"基本",
//基本手法
"hand":"基本",
//基本法术
"magic":"基本",
//基本杖法
"staff":"基本",
//基本掌法
"strike":"基本",
//基本泳技
"swimming":"基本",
//基本剑法
"sword":"基本",
//基本暗器
"throwing":"基本",
//基本拳脚
"unarmed":"基本",
//基本鞭法
"whip":"基本",
//艺术修养
"art-cognize":"知识",
//白驼秘传
"baituo-michuan":"知识",
//叫化绝活
"begging":"知识",
//碧海潮生曲
"bihai-chaosheng":"知识",
//禅宗心法
"buddhism":"知识",
//镶嵌技艺
"certosina":"知识",
//道听途说
"checking":"知识",
//义勇军进行曲
"chinese-anthem":"知识",
//痴心情长剑
"chixin-jian":"知识",
//川菜技艺
"chuancai-jiyi":"知识",
//吹箫技法
"chuixiao-jifa":"知识",
//阴阳八卦
"count":"知识",
//兵法修养
"craft-cognize":"知识",
//文学修养
"culture-cognize":"知识",
//妙手驱毒
"dispel-poison":"知识",
//绘画技巧
"drawing":"知识",
//驾车技术
"driving":"知识",
//养猪大法
"feed-power":"知识",
//御剑术
"fly":"知识",
//古筝技法
"guzheng-jifa":"知识",
//讨价还价
"higgling":"知识",
//发呆神功
"idle-force":"知识",
//密宗心法
"lamaism":"知识",
//炼丹术
"liandan-shu":"知识",
//读书写字
"literate":"知识",
//大乘涅磐功
"mahayana":"知识",
//武学修养
"martial-cognize":"知识",
//算术
"mathematics":"知识",
//基本医术
"medical":"知识",
//基本招架
"parry":"知识",
//渡世济人
"persuading":"知识",
//基本毒技
"poison":"知识",
//易容术
"pretending":"知识",
//奇门五行
"qimen-wuxing":"知识",
//清心普善咒
"qingxin-pushan":"知识",
//驱蜂术
"qufeng":"知识",
//梵文
"sanscrit":"知识",
//少林医术
"shaolin-yishu":"知识",
//蛇毒奇巧
"shedu-qiqiao":"知识",
//神龙秘辛
"shenlong-mixin":"知识",
//妙手空空
"stealing":"知识",
//剑道修养
"sword-cognize":"知识",
//弹琴技法
"tanqin-jifa":"知识",
//桃花药理
"taohua-yaoli":"知识",
//道学心法
"taoism":"知识",
//技术修养
"technic-cognize":"知识",
//驭兽术
"training":"知识",
//舞蛇曲
"wushe-qu":"知识",
//五行绝技
"wuxing-jueji":"知识",
//笑傲江湖曲
"xiaoao-jianghu":"知识",
//逍遥奇学
"xiaoyao-qixue":"知识",
//星宿奇术
"xingxiu-qishu":"知识",
//西域铁筝音
"xiyu-tiezheng":"知识",
//药王妙术
"yaowang-miaoshu":"知识",
//针灸术
"zhenjiu-shu":"知识",
//左右互搏
"zuoyou-hubo":"知识",
//太祖长拳
"changquan":"下品",
//缠魂索
"chanhun-suo":"下品",
//缠丝擒拿手
"chansi-shou":"下品",
//重阳神掌
"chongyang-shenzhang":"下品",
//丁字步
"ding-dodge":"下品",
//小丁气功
"ding-force":"下品",
//羝羊触蕃
"diyang-chufan":"下品",
//东洋刀法
"dongyang-dao":"下品",
//断云斧
"duanyun-fu":"下品",
//飞龙在天
"feilong-zaitian":"下品",
//飞星术
"feixing-shu":"下品",
//飞燕回翔
"feiyan-huixiang":"下品",
//飞檐走壁
"feiyan-zoubi":"下品",
//扶桑内功
"fushang-neigong":"下品",
//关冲剑
"guanchong-sword":"下品",
//光明掌法
"guangming-zhang":"下品",
//龟息功
"guixi-gong":"下品",
//昊天掌
"haotian-zhang":"下品",
//恒山剑法
"hengshan-jian":"下品",
//衡山剑法
"hengshan-sword":"下品",
//鸿渐于陆
"hongjian-yulu":"下品",
//猴拳
"houquan":"下品",
//华山拳法
"huashan-quanfa":"下品",
//华山身法
"huashan-shenfa":"下品",
//华山剑法
"huashan-sword":"下品",
//华山心法
"huashan-xinfa":"下品",
//华山掌法
"huashan-zhangfa":"下品",
//胡家拳法
"hujia-quan":"下品",
//或跃在渊
"huoyue-zaiyuan":"下品",
//虎爪绝嗣手
"huzhua-shou":"下品",
//见龙在田
"jianlong-zaitian":"下品",
//叫花棒法
"jiaohua-bangfa":"下品",
//叫花内功
"jiaohua-neigong":"下品",
//绝门棍
"juemen-gun":"下品",
//绝命腿
"jueming-tui":"下品",
//亢龙有悔
"kanglong-youhui":"下品",
//幽兰拂穴手
"lanhua-shou":"下品",
//烈火剑法
"liehuo-jian":"下品",
//烈焰刀
"lieyan-dao":"下品",
//灵鹫心法
"lingjiu-xinfa":"下品",
//灵蛇拳
"lingshe-quan":"下品",
//灵蛇杖法
"lingshe-zhangfa":"下品",
//凌虚步
"lingxu-bu":"下品",
//lingyuan-xinfa
"lingyuan-xinfa":"下品",
//利涉大川
"lishe-dachuan":"下品",
//流水鞭法
"liushui-bian":"下品",
//龙战于野
"longzhan-yuye":"下品",
//龙爪功
"longzhua-gong":"下品",
//罗汉拳
"luohan-quan":"下品",
//落英神剑
"luoying-shenjian":"下品",
//落英神掌
"luoying-shenzhang":"下品",
//落英心法
"luoying-xinfa":"下品",
//履霜冰至
"lvshuang-bingzhi":"下品",
//满天星
"mantian-xing":"下品",
//美女拳
"meinv-quan":"下品",
//密云不雨
"miyun-buyu":"下品",
//密宗内功
"mizong-neigong":"下品",
//排云推手
"paiyun-shou":"下品",
//飘渺身法
"piaomiao-shenfa":"下品",
//寒雪断云掌
"piaoxue-zhang":"下品",
//飘逸步法
"piaoyibu":"下品",
//霹雳刀法
"pili-daofa":"下品",
//霹雳神拳
"pili-quan":"下品",
//霹雳手
"pili-shou":"下品",
//胜邪剑法
"pixie-sword":"下品",
//劈石破玉拳
"poyu-quan":"下品",
//普渡杖
"pudu-zhang":"下品",
//潜龙勿用
"qianlong-wuyong":"下品",
//清凉打穴法
"qingliang-daxuefa":"下品",
//秋风拂尘
"qiufeng-chenfa":"下品",
//七星拳法
"qixing-quan":"下品",
//全真心法
"quanzhen-xinfa":"下品",
//取经棍法
"qujing-gunfa":"下品",
//忍术
"renshu":"下品",
//日月鞭法
"riyue-bian":"下品",
//日月剑法
"riyue-jian":"下品",
//如意刀
"ruyi-dao":"下品",
//六分剑术
"sanfen-jianshu":"下品",
//散花掌
"sanhua-zhang":"下品",
//六阴蜈蚣爪
"sanyin-wugongzhao":"下品",
//商阳剑
"shangyang-sword":"下品",
//少冲剑
"shaochong-sword":"下品",
//少林身法
"shaolin-shenfa":"下品",
//少林心法
"shaolin-xinfa":"下品",
//少商剑
"shaoshang-sword":"下品",
//少泽剑
"shaoze-sword":"下品",
//蛇岛内功
"shedao-neigong":"下品",
//圣火拳法
"shenghuo-quan":"下品",
//圣火心法
"shenghuo-xinfa":"下品",
//神龙摆尾
"shenlong-baiwei":"下品",
//神龙心法
"shenlong-xinfa":"下品",
//时乘六龙
"shicheng-liulong":"下品",
//石鼓打穴笔法
"shigu-bifa":"下品",
//双龙取水
"shuanglong-qushui":"下品",
//嵩山剑法
"songshan-sword":"下品",
//嵩山心法
"songshan-xinfa":"下品",
//损则有孚
"sunze-youfu":"下品",
//锁喉功
"suohou-gong":"下品",
//泰山剑法
"taishan-sword":"下品",
//泰山心法
"taishan-xinfa":"下品",
//taohua-zhangfa
"taohua-zhangfa":"下品",
//踏雪无痕
"taxue-wuhen":"下品",
//天长掌法
"tianchang-zhang":"下品",
//天罡指穴法
"tiangang-zhi":"下品",
//天罗地网
"tianluo-diwang":"下品",
//天南步法
"tiannan-step":"下品",
//天山杖法
"tianshan-zhang":"下品",
//天羽奇剑
"tianyu-qijian":"下品",
//透骨针
"tougu-zhen":"下品",
//突如其来
"turu-qilai":"下品",
//韦驮棍
"weituo-gun":"下品",
//无常杖
"wuchang-zhang":"下品",
//武当剑法
"wudang-jian":"下品",
//武当心法
"wudang-xinfa":"下品",
//五虎断门刀
"wuhu-duanmendao":"下品",
//舞剑术
"wujian-shu":"下品",
//巫月刀法
"wuyue-blade":"下品",
//无争心法
"wuzheng-xinfa":"下品",
//xiake-force
"xiake-force":"下品",
//逍遥心法
"xiaoyao-xinfa":"下品",
//修罗刀
"xiuluo-dao":"下品",
//修罗指
"xiuluo-zhi":"下品",
//西洋搏击术
"xiyang-boji":"下品",
//西洋剑术
"xiyang-jian":"下品",
//西洋内功
"xiyang-neigong":"下品",
//旋风扫叶腿
"xuanfeng-leg":"下品",
//玄虚刀法
"xuanxu-dao":"下品",
//须弥山掌
"xumishan-zhang":"下品",
//燕双飞
"yanfly":"下品",
//雁行刀
"yanxing-dao":"下品",
//阴风刀
"yinfeng-dao":"下品",
//金玲银索
"yinsuo-jinling":"下品",
//倚天屠龙掌
"yitian-zhang":"下品",
//意形步法
"yixingbu":"下品",
//一指禅
"yizhi-chan":"下品",
//越爪功
"yuezhao-gong":"下品",
//玉蜂针
"yufeng-zhen":"下品",
//金刚瑜迦母拳
"yujiamu-quan":"下品",
//瑜珈术
"yujiashu":"下品",
//云龙鞭法
"yunlong-bian":"下品",
//云龙身法
"yunlong-shenfa":"下品",
//云龙手
"yunlong-shou":"下品",
//云龙心法
"yunlong-xinfa":"下品",
//云龙爪
"yunlong-zhua":"下品",
//素女剑法
"yunu-sword":"下品",
//素女剑法
"yunv-jian":"下品",
//玉女身法
"yunv-shenfa":"下品",
//玉女心法
"yunv-xinfa":"下品",
//玉女心经
"yunv-xinjing":"下品",
//鱼跃于渊
"yuyue-yuyuan":"下品",
//摘星功
"zhaixinggong":"下品",
//震惊百里
"zhenjing-baili":"下品",
//震山掌
"zhenshan-zhang":"下品",
//中冲剑
"zhongchong-sword":"下品",
//终南指法
"zhongnan-zhi":"下品",
//中平枪法
"zhongping-qiang":"下品",
//周公剑
"zhougong-jian":"下品",
//紫金八卦刀
"zijinbagua-dao":"下品",
//少林醉棍
"zui-gun":"下品",
//醉拳
"zui-quan":"下品",
//暗影浮香
"anying-fuxiang":"中品",
//九天十地唯我至尊功
"bahuang-gong":"中品",
//百变打穴
"baibian-daxue":"中品",
//折花错拳
"baihua-quan":"中品",
//百胜刀法
"baisheng-daofa":"中品",
//般若掌
"banruo-zhang":"中品",
//北斗仙踪
"beidou-xianzong":"中品",
//蝙蝠步法
"bianfu-bu":"中品",
//清荷针掌
"bizhen-qingzhang":"中品",
//参星指
"canhe-zhi":"中品",
//蟾蜍步法
"chanchu-bufa":"中品",
//炼髓掌
"chousui-zhang":"中品",
//慈悲刀
"cibei-dao":"中品",
//密宗大手印
"dashou-yin":"中品",
//一横一勾拳
"ding-unarmed":"中品",
//段家剑
"duanjia-sword":"中品",
//段氏心法
"duanshi-xinfa":"中品",
//多罗叶指
"duoluoye-zhi":"中品",
//峨嵋心法
"emei-xinfa":"中品",
//反两仪刀法
"fanliangyi-dao":"中品",
//飞凤鞭
"feifeng-whip":"中品",
//疯魔杖法
"fengmo-zhang":"中品",
//风云手
"fengyun-shou":"中品",
//烈焰寒冰掌
"fireice-strike":"中品",
//五遁绝杀
"five-avoid":"中品",
//伏魔剑
"fumo-jian":"中品",
//二十四路伏魔杖
"fumo-zhang":"中品",
//大云光明经
"guangming-jing":"中品",
//寒冰绵掌
"hanbing-mianzhang":"中品",
//寒星八打
"hanxing-bada":"中品",
//回生决
"huisheng-jue":"中品",
//混天气功
"huntian-qigong":"中品",
//混元一气功
"hunyuan-yiqi":"中品",
//混元掌
"hunyuan-zhang":"中品",
//烈焰刀
"huoyan-dao":"中品",
//金佛绵掌
"jinding-zhang":"中品",
//大金刚拳
"jingang-quan":"中品",
//金刚指
"jingang-zhi":"中品",
//金关玉锁二十四诀
"jinguan-yusuo":"中品",
//腾蛇剑法
"jinshe-jian":"中品",
//腾蛇游身掌
"jinshe-zhang":"中品",
//腾蛇锥法
"jinshe-zhui":"中品",
//赤炼刀法
"jinwu-daofa":"中品",
//金雁功
"jinyan-gong":"中品",
//金玉拳
"jinyu-quan":"中品",
//玄阴炼骨爪
"jiuyin-baiguzhao":"中品",
//狂风刀法
"kuangfeng-blade":"中品",
//连风快剑
"kuangfeng-jian":"中品",
//葵花魔功
"kuihua-mogong":"中品",
//葵花心法
"kuihua-xinfa":"中品",
//昆仑剑法
"kunlun-jian":"中品",
//冷月神功
"lengyue-shengong":"中品",
//两仪剑法
"liangyi-jian":"中品",
//连环迷踪腿
"lianhuan-mizongtui":"中品",
//玉影流月剑
"liuyue-jian":"中品",
//龙城神刀
"longcheng-shendao":"中品",
//满天花雨掷金针
"mantianhuayu-zhen":"中品",
//苗家剑法
"miaojia-jian":"中品",
//不动明王剑
"mingwang-jian":"中品",
//慕容剑法
"murong-sword":"中品",
//降伏法
"necromancy":"中品",
//拈花指
"nianhua-zhi":"中品",
//如来千叶手
"qianye-shou":"中品",
//青蝠身法
"qingfu-shenfa":"中品",
//七丧拳
"qishang-quan":"中品",
//全真剑法
"quanzhen-jian":"中品",
//冷焰刀法
"ranmu-daofa":"中品",
//绕指柔剑
"raozhi-roujian":"中品",
//日月光华
"riyue-guanghua":"中品",
//日月轮法
"riyue-lun":"中品",
//日月心法
"riyue-xinfa":"中品",
//柔云步法
"rouyun-steps":"中品",
//如来神掌
"rulai-shenzhang":"中品",
//蛇岛奇功
"shedao-qigong":"中品",
//圣火步法
"shenghuo-bu":"中品",
//圣火令法
"shenghuo-ling":"中品",
//圣火神功
"shenghuo-shengong":"中品",
//身空行
"shenkong-xing":"中品",
//神龙八式
"shenlong-bashi":"中品",
//玄霄十三剑
"shenmen-jian":"中品",
//神行千变
"shenxing-baibian":"中品",
//神掌八打
"shenzhang-bada":"中品",
//四象步法
"sixiang-bufa":"中品",
//搜骨鹰爪功
"sougu-yingzhua":"中品",
//搜骨鹰爪功
"sougu":"中品",
//玄阳指
"sun-finger":"中品",
//怒海狂涛
"surge-force":"中品",
//太极刀法
"taiji-dao":"中品",
//太极剑法
"taiji-jian":"中品",
//弹指惊雷
"tanzhi-shentong":"中品",
//桃花怨
"taohua-yuan":"中品",
//天魔刀法
"tianmo-dao":"中品",
//日月天魔棍
"tianmo-gun":"中品",
//天魔剑法
"tianmo-jian":"中品",
//天魔掌法
"tianmo-zhang":"中品",
//梯云纵
"tiyunzong":"中品",
//武当绵掌
"wudang-zhang":"中品",
//绫罗青烟掌
"wuluo-zhang":"中品",
//无相指法
"wuxiang-zhi":"中品",
//五韵七弦剑
"wuyun-jianfa":"中品",
//金刚降魔杵
"xiangmo-chu":"中品",
//降魔杖法
"xiangmo-zhangfa":"中品",
//無相玄功
"xiaowuxiang":"中品",
//逍遥剑法
"xiaoyao-jian":"中品",
//逍遥游
"xiaoyaoyou":"中品",
//吸功大法
"xixing-dafa":"中品",
//玄冥神功
"xuanming-shengong":"中品",
//天幽神掌
"xuanming-zhang":"中品",
//玄天神功
"xuantian-shengong":"中品",
//玄天无情指
"xuantian-zhi":"中品",
//轩辕箭
"xuanyuan-arrow":"中品",
//血海魔功
"xuehai-mogong":"中品",
//虚无缥缈
"xuwu-piaomiao":"中品",
//易筋锻骨
"yijin-duangu":"中品",
//鹰爪功
"yingzhua-gong":"中品",
//一拍两散
"yipai-liangsan":"中品",
//云龙剑
"yunlong-jian":"中品",
//云龙神功
"yunlong-shengong":"中品",
//折梅手
"zhemei-shou":"中品",
//追风步
"zhuifeng-steps":"中品",
//追魂夺命剑
"zhuihun-jian":"中品",
//诸天化身步
"zhutian-bu":"中品",
//紫徽心法
"zihui-xinfa":"中品",
//紫霞神功
"zixia-shengong":"中品",
//碧波神功
"bibo-shengong":"中品",
//催心掌
"cuixin-zhang":"中品",
//化灵大法
"huagong-dafa":"中品",
//销骨绵掌
"huagu-mianzhang":"中品",
//幻魔胧天舞
"huanmo-longtianwu":"中品",
//玄阴指
"huanyin-zhi":"中品",
//回风拂柳剑
"huifeng-jian":"中品",
//达摩剑
"damo-jian":"中品",
//六阳掌
"liuyang-zhang":"中品",
//空灵拳
"kongming-quan":"中品",
//枯荣禅功
"kurong-changong":"中品",
//青冥神功
"beiming-shengong":"上品",
//神丐棒法
"dagou-bang":"上品",
//移星换斗
"douzhuan-xingyi":"上品",
//镇岳锁龙劲
"dragon-strike":"上品",
//冰蚕寒功
"freezing-force":"上品",
//蛤蟆功
"hamagong":"上品",
//飞狐刀法
"hujia-daofa":"上品",
//金刚不坏体
"jingang-buhuaiti":"上品",
//临济十二庄
"linji-zhuang":"上品",
//龙象般若功
"longxiang":"上品",
//败血伸爪
"ningxue-shenzhao":"上品",
//胜邪剑法
"pixie-jian":"上品",
//乾坤大挪移
"qiankun-danuoyi":"上品",
//六阴殛神掌
"sad-strike":"上品",
//玄照经神功
"shenzhaojing":"上品",
//玄阴步
"shexing-lifan":"上品",
//太极神功
"taiji-shengong":"上品",
//太玄功
"taixuan-gong":"上品",
//周天功
"xiantian-gong":"上品",
//补天剑诀
"xuantie-jian":"上品",
//血河神刀
"xue-dao":"上品",
//越女剑术
"yuenv-jian":"上品",
//云箫剑法
"yuxiao-jian":"上品",
//六极神剑
"six-finger":"宗师",
//太极拳
"taiji-quan":"宗师",
//南海玄功
"bluesea-force":"宗师",
//洛神步法
"lingbo-weibu":"宗师",
//紫阳神功
"jiuyang-shengong":"宗师",
//九阴神功
"jiuyin-shengong":"宗师",
//葵花神功
"kuihua-shengong":"宗师",
//九剑归一
"lonely-sword":"宗师",
//不败神功
"never-defeated":"宗师",
//易筋经神功
"yijinjing":"宗师",

]);